#!/usr/bin/python
# A simple CLI expense tracker
import argparse, json, datetime, csv
from contextlib import contextmanager

@contextmanager
def open_expenses():
    expenses = []
    try:
        with open('expenses.json', 'r') as f:
            expenses = json.load(f)
    except Exception as e:
            expenses = []

    yield expenses

    try:
        with open('expenses.json', 'w') as f:
            json.dump(expenses, f)
    except Exception as e:
        print(f'Error while writing json to file: {e}')

def on_add(args) -> None:
    with open_expenses() as all_expenses:
        if all_expenses:
            last_id = all_expenses[-1]['id']
        else:
            last_id = 0
        expense_text = ' '.join(args.description)
        if not expense_text:
            print('Error: the description cannot be empty')
            return
        all_expenses.append({ 'id': last_id+1,
                     'description': expense_text,
                     'amount': args.amount,
                     'date': str(datetime.date.today()),
                     'category': args.category if args.category else 'Other'
                })

def export_to_csv(args) -> None:
    csv_filename = args.file if args.file else 'export.csv'
    delimiter = args.delimiter if args.delimiter else ','
    with open_expenses() as all_expenses:
        with open(csv_filename, 'w', newline='') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=[k for k in all_expenses[0].keys()], delimiter=delimiter, quotechar='"', quoting=csv.QUOTE_MINIMAL)
            writer.writeheader()
            for row in all_expenses:
                writer.writerow(row)

def import_from_csv(args) -> None:
    csv_filename = args.file if args.file else 'export.csv'
    delimiter = args.delimiter if args.delimiter else ','
    with open_expenses() as all_expenses:
        all_expenses.clear()
        with open(csv_filename, 'r', newline='') as csvfile:
            reader = csv.DictReader(csvfile, delimiter=delimiter, quotechar='"')
            for row in reader:
                all_expenses.append(row)
    

def on_remove(args) -> None:
    with open_expenses() as all_expenses:
        for expense in all_expenses:
            if expense['id'] == args.id:
                all_expenses.remove(expense)
                return
        else:
            print(f'Task with id {args.id} not found')

def on_update(args) -> None:
    with open_expenses() as all_expenses:
        for expense in all_expenses:
            if expense['id'] == args.id:
                if args.description:
                    expense['description'] = args.description
                if args.amount:
                    expense['amount'] = args.amount
                if args.category:
                    expense['category'] = args.category
                return
        else:
            print(f'Task with id {args.id} not found')

def list_expenses(args) -> None:
    with open_expenses() as all_expenses:
    
        ID_WIDTH = 5
        DESC_WIDTH = max((len(expense['description']) for expense in all_expenses), default=20)
        AMOUNT_WIDTH = 15
        TIME_WIDTH = 20
        CATEGORY_WIDTH = 20
        header = (
            f"{'ID'.ljust(ID_WIDTH)} | "
            f"{'Description'.ljust(DESC_WIDTH)} | "
            f"{'Amount'.ljust(AMOUNT_WIDTH)} | "
            f"{'Date'.ljust(TIME_WIDTH)} | "
            f"{'Category'.ljust(CATEGORY_WIDTH)} | "
        )
        print(header)
        print('-' * len(header))

        for expense in all_expenses:
            row = (
                f"{str(expense['id']).ljust(ID_WIDTH)} | "
                f"{expense['description'].ljust(DESC_WIDTH)} | "
                f"{str(expense['amount']).ljust(AMOUNT_WIDTH)} | "
                f"{expense['date'].ljust(TIME_WIDTH)} | "
                f"{expense['category'].ljust(CATEGORY_WIDTH)} |"
            )
            print(row)

def summary_expenses(args) -> None:
    months = ['January', 'Febrary', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    with open_expenses() as all_expenses:
        current_year = datetime.date.today().year
        needed_expenses = [
            expense for expense in all_expenses
            if (
                (not args.month or int(expense['date'].split('-')[1]) == args.month) and
                (not args.category or expense['category'] == args.category) and
                int(expense['date'].split('-')[0]) == current_year
            )
        ]

        total_amount = sum(expense['amount'] for expense in needed_expenses)

        if args.month:
            print(f'Total expenses for {months[args.month-1]}: ${total_amount}')
        else:
            print(f'Total expenses: ${total_amount}')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
            prog='expense-tracker',
            description='A simple CLI expense tracker'
            )
    subparsers = parser.add_subparsers(required=True)
    
    commands = [
        {
            'name': 'add',
            'help': 'Add a new expense',
            'arguments': [
                {'name': '--description', 'nargs': '+', 'required': True, 'help': 'Expense description'},
                {'name': '--amount', 'type': int, 'required': True, 'help': 'Expense amount'},
                {'name': '--category',  'help': 'Expense category'}
            ],
            'func': on_add
        },
        {
            'name': 'delete',
            'help': 'Remove an expense',
            'arguments': [
                {'name': '--id', 'type': int, 'required': True, 'help': 'Expense id'}
            ],
            'func': on_remove
        },
        {
            'name': 'update',
            'help': 'Update an expense',
            'arguments': [
                {'name': '--id', 'type': int, 'required': True, 'help': 'Expense id'},
                {'name': '--description', 'nargs': '+', 'help': 'Expense description'},
                {'name': '--amount', 'type': int, 'help': 'Expense amount'},
                {'name': '--category',  'help': 'Expense category'}
            ],
            'func': on_update
        },
        {
            'name': 'list',
            'help': 'List expenses',
            'arguments': [],
            'func': list_expenses
        },
        {
            'name': 'summary',
            'help': 'Summary expenses',
            'arguments': [
                {'name': '--month', 'type': int, 'nargs': '?', 'help': 'Show summary'},
                {'name': '--category',  'help': 'Expense category'}
            ],
            'func': summary_expenses
        },
        {   'name': 'export',
            'help': 'export expenses to csv file',
            'arguments': [
                {'name': '--file', 'help': 'Filename for export'},
                {'name': '--delimiter', 'help': 'Delimiter in csv file'}
            ],
            'func': export_to_csv

        },
        {   'name': 'import',
            'help': 'import expenses from csv',
            'arguments': [
                {'name': '--file', 'help': 'CSV filename'},
                {'name': '--delimiter', 'help': 'Delimiter in csv file'}
            ],
            'func': import_from_csv


        }
    ]
    
    for command in commands:
        cmd_parser = subparsers.add_parser(command['name'], help=command['help'])
        for arg in command['arguments']:
            cmd_parser.add_argument(arg['name'], **{k: v for k, v in arg.items() if k != 'name'})
        cmd_parser.set_defaults(func=command['func'])

    args = parser.parse_args()
    args.func(args)
